language: es

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
    dimensions:
      - number
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper

policies:
  - name: FallbackPolicy
#   - name: TEDPolicy
#     epochs: 3
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
